# Generated by Django 6.0.6 on 2026-06-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-Stock', 'Out-Stock')], max_length=50, null=True),
        ),
    ]
